# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

User.destroy_all
chithra =User.create(username: 'chithra', password: 'password', email: 'chithra@chithra.com')
guest = User.create(username: 'SPICY', password: 'password', email:'spicy@spicy.com')
luke = User.create(username: "luke_skywalker", password:"password", email: "luke@starwars.com",image: File.open('app/assets/images/luke.jpg'))
beyonce = User.create(username: "queen_bey", password:"password", email: "queen_bey@gmail.com",image: File.open('app/assets/images/beyonce.jpg'))
oprah = User.create(username: "oprah", password:"password", email: "oprah@gmail.com",image: File.open('app/assets/images/oprah.jpg'))
kim = User.create(username: "kim", password:"password", email: "kim@gmail.com",image: File.open('app/assets/images/kim.jpg'))
rachel = User.create(username: "rachel_ray", password:"password", email: "rachel_ray@gmail.com",image: File.open('app/assets/images/rachel.jpg'))
guy = User.create(username: "guy_fieri", password:"password", email: "guy_fieri@gmail.com",image: File.open('app/assets/images/guy.jpg'))
bill = User.create(username: "bill_gates", password:"password", email: "bill_gates@gmail.com",image: File.open('app/assets/images/bill.jpg'))
trumpye = User.create(username: "trump_kanye", password:"password", email: "trump_kanye@gmail.com",image: File.open('app/assets/images/trumpye.jpg'))
meowth = User.create(username: "meowth", password:"password", email: "meowth@gmail.com",image: File.open('app/assets/images/meowth.jpg'))
bulbasaur = User.create(username: "bulbasaur", password:"password", email: "bulbasaur@gmail.com",image: File.open('app/assets/images/bulbasaur.jpg'))
ash = User.create(username: "ash_ketchum", password:"password", email: "ash_ketchum@gmail.com",image: File.open('app/assets/images/ash.jpg'))
bigbird = User.create(username: "big_bird", password:"password", email: "big_bird@gmail.com",image: File.open('app/assets/images/bigbird.jpg'))
cookie = User.create(username: "cookie_monster", password:"password", email: "cookie_monster@gmail.com",image: File.open('app/assets/images/cookie.jpg'))
meangirls = User.create(username: "mean_girls", password:"password", email: "mean_girls@gmail.com",image: File.open('app/assets/images/meangirls.jpg'))

SauceCompany.destroy_all
secret_aardvark = SauceCompany.create(name: 'Secret Aardvark')
tabasco = SauceCompany.create(name: 'TABASCO')
cholula = SauceCompany.create(name: 'Cholula')
tapatio = SauceCompany.create(name: 'Tapatio')
huy_fong = SauceCompany.create(name: 'Huy Fong')
bravado = SauceCompany.create(name: 'Bravado Spice Co.')
nandos = SauceCompany.create(name: "Nando's")
el_yucateco = SauceCompany.create(name: "El Yucateco")
mad_dog = SauceCompany.create(name: "Mad Dog's Revenge")
widow = SauceCompany.create(name: "Widow")


Sauce.destroy_all
sriracha = Sauce.create(name: "Sriracha", description:"Our most popular sauce", scoville_units: 2200,image: File.open('app/assets/images/sriracha.jpg'), company_id: huy_fong.id)
tabasco = Sauce.create(name: "Original Red", description:"TABASCO® brand Original Red Sauce owes much of its unique, pungent flavor to the handcrafted way it’s been made for over 140 years. Equally important is the heart of the one family who created this world-famous sauce as a labor of love", scoville_units: 2500,image: File.open('app/assets/images/tabasco.jpg'), company_id: tabasco.id)
yucateco_green = Sauce.create(name: "Habanero Green", description:"From Merida, Yucatan, Mexico, this is the hotter of the two original El Yucateco colors. Elaborated with another of our classic recipes based on green habanero peppers, garlic and spices. This special blend of ingredients gives a fresh, home flavor to the meals.", scoville_units: 8910,image: File.open('app/assets/images/yucateco_green.png'), company_id: el_yucateco.id)
xxxtra_hot = Sauce.create(name: "Habanero XXXTra Hot Habanero", description:"El Yucateco Salsa Picante de Chile Habanero XXXTra Hot Habanero Hot Sauce (4 FL.OZ. / 120 ml): Weighing in at about 11,000 scovilles units, this is by far the hottest of the wonderful line of sauces from Merida, Yucatan, Mexico.", scoville_units: 11600,image: File.open('app/assets/images/xxxtra_hot.jpg'), company_id: el_yucateco.id)
picante_negra = Sauce.create(name: "Black Label Reserve", description:"El Yucateco Black Label Reserve Chile Habanero From Mexico", scoville_units: 11000,image: File.open('app/assets/images/picante_negra.jpg'), company_id: el_yucateco.id)
secret_habanero = Sauce.create(name: "HABANERO HOT SAUCE", description:"Portland's famous table sauce, Secret Aardvark Habanero's unique Caribbean / Tex-Mex hybrid is made with flavorful Habanero peppers and roasted tomatoes. You'll want to use it on everything, so be careful if you only get one bottle.", scoville_units: 2000,image: File.open('app/assets/images/secret_habanero.jpg'), company_id: secret_aardvark.id)
secret_drunken = Sauce.create(name: "DRUNKEN JERK SAUCE", description:"Scotch Bonnet & Habanero peppers give this Jamaican-style Jerk sauce some serious heat. A touch of Caribbean dark rum keeps things cool & easy. Try this as a marinade on your favorite chicken or veggies to bring a bit of tropical sunshine to the dinner table.", scoville_units: 1000,image: File.open('app/assets/images/secret_drunken.jpg'), company_id: secret_aardvark.id)
tabasco_chipotle = Sauce.create(name: "Chipotle Pepper Sauce", description:"Even before the time of the Aztecs, ancient Mexican civilizations prized the chipotle pepper for its dark, smoky flavor. Now we’ve perfected our own method of smoking vine-ripened, red jalapeño peppers over a smoldering fire to make TABASCO® brand Chipotle Pepper Sauce—a rich, thick-bodied sauce ideally balanced in heat and flavor.", scoville_units: 2500,image: File.open('app/assets/images/tabasco_chipotle.jpg'), company_id: tabasco.id)
cholula_original = Sauce.create(name: "Original", description:"Hot and tangy red hot sauce from chile de arbol, piquin pepper and spices. Cholula Mexican Hot Sauce is great A Novamex product. CHOLULA HOT SAUCE INFO Cholula Hot Sauce is the fastestgrowing premium Mexican hot sauce in the U.S market. It has been imported from Mexico since 1988. ", scoville_units: 3600,image: File.open('app/assets/images/cholula_original.jpg'), company_id: cholula.id)
maddog_revenge = Sauce.create(name: "Habanero & Chile Extract", description:"It takes over 12 pounds of smokin' hot peppers to make 1 bottle of Mad Dog's Revenge Habanero & Chile Extract. Great Flavor and unbelievable heat.", scoville_units: 1000000,image: File.open('app/assets/images/maddog_revenge.jpg'), company_id: mad_dog.id)
widow_nosurvivor = Sauce.create(name: "No Survivors Hot Sauce", description:"Scared of Spider's? This one bites, and there are no survivors.", scoville_units: 90000,image: File.open('app/assets/images/widow_nosurvivors.jpg'), company_id: widow.id)

Checkin.destroy_all
Checkin.create(user_id: guest.id, sauce_id: sriracha.id, overall_rating: 3, heat_rating: 2, comment: "kinda basic imo, even hipsters like it")
Checkin.create(user_id: kim.id, sauce_id: picante_negra.id, overall_rating: 2, heat_rating: 3, comment: "Ugh idk.")
Checkin.create(user_id: bulbasaur.id, sauce_id: secret_habanero.id, overall_rating: 5, heat_rating: 3, comment: "Bulbbbaaaa.")
Checkin.create(user_id: kim.id, sauce_id: sriracha.id, overall_rating: 5, heat_rating: 1, comment: "Basic, just like me. luv it.")
Checkin.create(user_id: oprah.id, sauce_id: secret_drunken.id, overall_rating: 5, heat_rating: 2, comment: "I love marinating everything with this.")
Checkin.create(user_id: beyonce.id, sauce_id: tabasco.id, overall_rating: 1, heat_rating: 1, comment: "Too basic.")
Checkin.create(user_id: bill.id, sauce_id: secret_habanero.id, overall_rating: 5, heat_rating: 2, comment: "Worth its weight in gold.")
Checkin.create(user_id: luke.id, sauce_id: widow_nosurvivor.id, overall_rating: 2, heat_rating: 4, comment: "This is a 4.5- not sure why I tried it. Actually, I do know. Han Solo. ugh.")
Checkin.create(user_id: bulbasaur.id, sauce_id: widow_nosurvivor.id, overall_rating: 4, heat_rating: 4, comment: "Bulbbbaaaa.")
Checkin.create(user_id: meangirls.id, sauce_id: tabasco_chipotle.id, overall_rating: 5, heat_rating: 2, comment: "Fetch.")
Checkin.create(user_id: oprah.id, sauce_id: xxxtra_hot.id, overall_rating: 4, heat_rating: 3, comment: "Very spicy, as expected from  a Yucateco.")
Checkin.create(user_id: luke.id, sauce_id: tabasco.id, overall_rating: 1, heat_rating: 2, comment: "I only eat this when I have to choose between this and battling 1000 storm troopers.")
Checkin.create(user_id: beyonce.id, sauce_id: widow_nosurvivor.id, overall_rating: 2, heat_rating: 5, comment: "I would trade my fabulous hair to get this burn out of my tummy.")
Checkin.create(user_id: luke.id, sauce_id: maddog_revenge.id, overall_rating: 1, heat_rating: 5, comment: "even Yoda couldnt handle this one")
Checkin.create(user_id: trumpye.id, sauce_id: widow_nosurvivor.id, overall_rating: 5, heat_rating: 5, comment: "Hot like Kanye, Ridiculous like Donald.")
Checkin.create(user_id: meowth.id, sauce_id: sriracha.id, overall_rating: 5, heat_rating: 2, comment: "Meeeeowthh.")
Checkin.create(user_id: meangirls.id, sauce_id: tabasco.id, overall_rating: 2, heat_rating: 1, comment: "The worst.")
Checkin.create(user_id: meowth.id, sauce_id: picante_negra.id, overall_rating: 3, heat_rating: 3, comment: "Meeeeowthh.")
Checkin.create(user_id: meowth.id, sauce_id: yucateco_green.id, overall_rating: 5, heat_rating: 3, comment: "Meeeeowthh.")
Checkin.create(user_id: kim.id, sauce_id: tabasco.id, overall_rating: 4, heat_rating: 2, comment: "Seriously mainstream. I think Kris would like this.")
Checkin.create(user_id: bill.id, sauce_id: secret_drunken.id, overall_rating: 4, heat_rating: 1, comment: "It might be time to invest in this. Great as a marinade on the backyard barby.")
Checkin.create(user_id: rachel.id, sauce_id: yucateco_green.id, overall_rating: 5, heat_rating: 3, comment: "Great as a spash on my sammies.")
Checkin.create(user_id: oprah.id, sauce_id: cholula_original.id, overall_rating: 2, heat_rating: 2, comment: "One of my favourites. I even gave it away on my favorite things episode.")
Checkin.create(user_id: guest.id, sauce_id: secret_habanero.id, overall_rating: 5, heat_rating: 2, comment: "best heat to taste ratio imo")
Checkin.create(user_id: kim.id, sauce_id: secret_drunken.id, overall_rating: 3, heat_rating: 1, comment: "Too mild. Might be better for Kendall.")
Checkin.create(user_id: meangirls.id, sauce_id: maddog_revenge.id, overall_rating: 1, heat_rating: 5, comment: "YOU CANT SIT WITH US!")
Checkin.create(user_id: beyonce.id, sauce_id: maddog_revenge.id, overall_rating: 1, heat_rating: 5, comment: "Im a survivor, I'm going to make it. ugh oh no.")
Checkin.create(user_id: guy.id, sauce_id: picante_negra.id, overall_rating: 5, heat_rating: 3, comment: "I take this to my diners, drive-ins, and dives.")
Checkin.create(user_id: rachel.id, sauce_id: sriracha.id, overall_rating: 2, heat_rating: 2, comment: "Everyone knows about it and now it's dead.")
Checkin.create(user_id: luke.id, sauce_id: secret_habanero.id, overall_rating: 4, heat_rating: 3, comment: "A true classic, much like Leia's hair.")
Checkin.create(user_id: meangirls.id, sauce_id: widow_nosurvivor.id, overall_rating: 1, heat_rating: 5, comment: "Is butter a carb? If so, I need some to difure the heat.")
Checkin.create(user_id: bulbasaur.id, sauce_id: secret_drunken.id, overall_rating: 5, heat_rating: 1, comment: "Bulbbbaaaa.")
Checkin.create(user_id: beyonce.id, sauce_id: secret_habanero.id, overall_rating: 5, heat_rating: 2, comment: "This is the hot sauce I keep in my bag, in case you were wondering.")
Checkin.create(user_id: luke.id, sauce_id: yucateco_green.id, overall_rating: 5, heat_rating: 3, comment: "the force is with this one")
Checkin.create(user_id: meangirls.id, sauce_id: cholula_original.id, overall_rating: 5, heat_rating: 2, comment: "We luv this one.")
Checkin.create(user_id: luke.id, sauce_id: tabasco_chipotle.id, overall_rating: 3, heat_rating: 2, comment: "Had this at chipotle ironically, but not my style. ")
Checkin.create(user_id: meowth.id, sauce_id: tabasco_chipotle.id, overall_rating: 4, heat_rating: 2, comment: "Meeeeowthh.")
Checkin.create(user_id: luke.id, sauce_id: sriracha.id, overall_rating: 2, heat_rating: 2, comment: "meh. this is more C3PO's type of sauce")
Checkin.create(user_id: oprah.id, sauce_id: widow_nosurvivor.id, overall_rating: 1, heat_rating: 5, comment: "Not sure why I did this.")
Checkin.create(user_id: kim.id, sauce_id: xxxtra_hot.id, overall_rating: 5, heat_rating: 5, comment: "I like this one bc we share the same attribute- XXXTRA HOT.")
Checkin.create(user_id: rachel.id, sauce_id: widow_nosurvivor.id, overall_rating: 3, heat_rating: 5, comment: "Could use some evoo.")
Checkin.create(user_id: bulbasaur.id, sauce_id: sriracha.id, overall_rating: 2, heat_rating: 2, comment: "Bulbbbaaaa.")
Checkin.create(user_id: beyonce.id, sauce_id: sriracha.id, overall_rating: 3, heat_rating: 2, comment: "This is basic. Like Rachel Roy. Oops did I just go there?")
